version: "3.8"

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./db:/data/db
      - mongo_data:/data/configdb
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./sloppy:/app/sloppy
    command: uv run celery -A sloppy.celery_app worker --loglevel=info -E

  flower:
    build: .
    depends_on:
      - redis
      - celery-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./sloppy:/app/sloppy
    ports:
      - "5555:5555"
    command: uv run celery -A sloppy.celery_app flower --basic-auth=admin:password --port=5555 --address=0.0.0.0
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
